# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        go build -v ./...
        pwd

    - name: Test
      run: go test -v ./...

    - name: Upload Go results
      uses: actions/upload-artifact@v4
      with:
        name: http-server
        path: /home/runner/work/http-server/http-server

  dockerfile:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@master
        with:
          name: http-server
          path: /home/runner/work/http-server/http-server

      - id: create_docker_tags
        run: |
          echo "::set-output name=tags::latest,$(git tag -l --sort=-v:refname | head -1)"
          echo ${{ steps.create_docker_tags.outputs.tags }}
        
      - uses: jerray/publish-docker-action@v1.0.5
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tags: ${{ steps.create_docker_tags.outputs.tags }}
            registry: registry.cn-hangzhou.aliyuncs.com
            repository: joeyzz/http-server